name: build

on:
  pull_request: ~
  push:
    branches: [cds-sample-app]
    paths:
      - 'samples/cds-sample-application'
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd samples/cds-sample-application
      - run: npm install
        env:
          CLOUD_DESTINATION_URL: https://my-destination-url.com
      - run: npm run ci-build
      - run: npm run test:e2e
